update
Signed-off-by: laurentsimon <laurentsimon@google.com>

diff --git a/actions/generator/generic/create-base64-subjects-from-file/action.yml b/actions/generator/generic/create-base64-subjects-from-file/action.yml
--- a/actions/generator/generic/create-base64-subjects-from-file/action.yml
+++ b/actions/generator/generic/create-base64-subjects-from-file/action.yml
@@ -40,6 +40,10 @@ runs:
         set -euo pipefail
 
         name=$(basename "${UNTRUSTED_PATH}")
+        if [[ -z "${UNTRUSTED_PATH}" ]]; then
+          echo "error: empty path"
+          exit 1
+        fi
         echo "artifact_name=${name}-${RNG}" >> "$GITHUB_OUTPUT"
         echo "filename=${name}" >> "$GITHUB_OUTPUT"
 
