Add outputs
Signed-off-by: Ian Lewis <ianlewis@google.com>

diff --git a/.github/workflows/builder_nodejs_slsa3.yml b/.github/workflows/builder_nodejs_slsa3.yml
--- a/.github/workflows/builder_nodejs_slsa3.yml
+++ b/.github/workflows/builder_nodejs_slsa3.yml
@@ -75,6 +75,27 @@ on:
         description: "The npm registry auth token used to publish the package."
         required: true
 
+    outputs:
+      artifact-name:
+        description: "The name of the package artifact uploaded to the workflow run."
+        value: ""
+
+      provenance-name:
+        description: "The name of the provenance attestation uploaded to the workflow run."
+        value: ""
+
+      release-asset-name:
+        description: "The package asset name uploaded to the release (if upload-assets is true). e.g. sigstore-1.1.1.tgz"
+        value: ""
+
+      release-id:
+        description: "The name of the release where the package tarball and provenance were uploaded (if upload-assets is true)."
+        value: ${{ jobs.slsa-publish.outputs.release-id }}
+
+      release-provenance-name:
+        description: "The provenance asset name uploaded to the release (if upload-assets is true). e.g. sigstore-1.1.1.intoto.jsonl"
+        value: ""
+
 jobs:
   slsa-setup:
     permissions:
@@ -107,6 +128,8 @@ jobs:
 
   slsa-publish:
     needs: [slsa-run]
+    outputs:
+      release-id: ${{ steps.release.outputs.id }}
     if: ${{ inputs.npm-publish }}
     permissions:
       contents: write # For asset uploads. Optional
@@ -258,9 +281,9 @@ jobs:
           "$(dirname "$(which node)")"/node_modules/npm/bin/npm publish "${PACKAGE_PATH}" ${publish_flags}
 
       - name: Upload provenance new tag
+        id: release-new-tags
         uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
         if: inputs.upload-assets && startsWith(github.ref, 'refs/tags/')
-        id: release-new-tags
         with:
           prerelease: ${{ inputs.prerelease }}
           files: |
@@ -269,6 +292,7 @@ jobs:
           draft: ${{ inputs.draft-release }}
 
       - name: Upload provenance tag name
+        id: release-tag-name
         uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
         if: inputs.upload-assets && inputs.upload-tag-name != ''
         with:
@@ -278,3 +302,23 @@ jobs:
             ${{ steps.validate-outputs.outputs.attestation-path }}
             ${{ steps.validate-outputs.outputs.package-path }}
           draft: ${{ inputs.draft-release }}
+
+      - name: Output release ID
+        shell: bash
+        id: release
+        env:
+          RELEASE_ID_NEW_TAGS: "${{ steps.release-new-tags.outputs.id }}"
+          RELEASE_ID_TAG_NAME: "${{ steps.release-tag-name.outputs.id }}"
+        run: |
+          set -euo pipefail
+          id=""
+          if [[ -n "$RELEASE_ID_NEW_TAGS" ]]; then
+            id="$RELEASE_ID_NEW_TAGS"
+          elif [[ -n "$RELEASE_ID_TAG_NAME" ]]; then
+            id="$RELEASE_ID_TAG_NAME"
+          else
+            # This should never happen (unless previous steps fail).
+            echo "internal error"
+            exit 1
+          fi
+          echo "id=$id" >> "$GITHUB_OUTPUT"
