update
Signed-off-by: laurentsimon <laurentsimon@google.com>

diff --git a/.github/workflows/generator_container_slsa3.yml b/.github/workflows/generator_container_slsa3.yml
--- a/.github/workflows/generator_container_slsa3.yml
+++ b/.github/workflows/generator_container_slsa3.yml
@@ -65,7 +65,7 @@ on:
       outcome:
         description: "The outcome status of the run ('success' or 'failure')."
         value: ${{ jobs.final.outputs.outcome }}
-  
+
 jobs:
   # detect-env detects the reusable workflow's repository and ref for use later
   # in the workflow.
@@ -180,14 +180,18 @@ jobs:
   # final fails or succeeds based on the value of `inputs.continue-on-error`
   # and the outcome of previous jobs.
   final:
+    outputs:
+      outcome: ${{ steps.final.outputs.outcome }}
     runs-on: ubuntu-latest
     needs: [detect-env, generator]
     # Note: always run even if needed jobs are skipped.
     if: always()
     steps:
       - name: Final outcome
+        id: final
         env:
           SUCCESS: ${{ needs.detect-env.outputs.outcome != 'failure' && steps.generator.outputs.outcome != 'failure' }}
           CONTINUE: ${{ inputs.continue-on-error }}
         run: |
+          echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
           [ "$CONTINUE" == "true" ] || [ "$SUCCESS" == "true" ] || exit 27
