update
Signed-off-by: laurentsimon <laurentsimon@google.com>

diff --git a/.github/workflows/generator_generic_slsa3.yml b/.github/workflows/generator_generic_slsa3.yml
--- a/.github/workflows/generator_generic_slsa3.yml
+++ b/.github/workflows/generator_generic_slsa3.yml
@@ -38,6 +38,10 @@ on:
         required: false
         type: boolean
         default: false
+      upload-url:
+        description: "If non-empty, the provenance is uploaded to the GitHub release idenified by the URL."
+        type: string
+        default: ""
       attestation-name:
         description: "The artifact name of the signed provenance. The file must have the intoto.jsonl extension. Defaults to <filename>.intoto.jsonl for single artifact or multiple.intoto.jsonl for multiple artifacts. DEPRECATED: Use provenance-name instead."
         required: false
@@ -63,8 +67,8 @@ on:
         default: false
     outputs:
       release-id:
-        description: "The name of the release where provenance was uploaded."
-        value: ${{ jobs.create-release.outputs.release-id }}
+        description: "The name of the release where provenance was uploaded. (Only for new tags)."
+        value: ${{ jobs.upload-tag.outputs.release-id }}
       attestation-name:
         description: "DEPRECATED: use the provenance-name output instead."
         value: ${{ jobs.generator.outputs.provenance-name }}
@@ -194,10 +198,10 @@ jobs:
       outcome: ${{ steps.final.outputs.outcome }}
       release-id: ${{ steps.release.outputs.id }}
     runs-on: ubuntu-latest
-    needs: [generator, detect-env]
+    needs: [generator]
     permissions:
       contents: write # Needed to write artifacts to a release.
-    if: startsWith(github.ref, 'refs/tags/') && inputs.upload-assets == true
+    if: inputs.upload-assets == true
     steps:
       - name: Checkout builder repository
         id: checkout-builder
@@ -217,18 +221,46 @@ jobs:
           path: "${{ needs.generator.outputs.provenance-name }}"
           sha256: "${{ needs.generator.outputs.provenance-sha256 }}"
 
-      - name: Release
-        id: release
-        continue-on-error: true
-        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
+      - name: Upload provenance new tag
+        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # tag=v0.1.14
+        if: startsWith(github.ref, 'refs/tags/') && inputs.upload-tag-name == ''
+        id: release-new-tags
         with:
           files: |
             ${{ needs.generator.outputs.provenance-name }}
 
+      - name: Upload provenance tag name
+        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # tag=v0.1.14
+        if: inputs.upload-tag-name != ''
+        id: release-tag-name
+        with:
+          tag_name: "${{ inputs.upload-tag-name }}"
+          files: |
+            ${{ needs.generator.outputs.provenance-name }}
+
+      - name: Output release ID
+        shell: bash
+        id: release
+        env:
+          RELEASE_ID_NEW_TAGS: "${{ steps.release-new-tags.outputs.id }}"
+          RELEASE_ID_TAG_NAME: "${{ steps.release-tag-name.outputs.id }}"
+        run: |
+          set -euo pipefail
+          id=""
+          if [[ -n "$RELEASE_ID_NEW_TAGS"]]; then
+            id="$RELEASE_ID_NEW_TAGS"
+          elif [[ -n "$RELEASE_ID_TAG_NAME"]]; then
+            id="$RELEASE_ID_TAG_NAME"
+          else
+            echo "internal error"
+            exit 1
+          fi
+          echo "::set-output name=id::$id"
+
       - name: Final outcome
         id: final
         env:
-          SUCCESS: ${{ steps.checkout-builder.outcome != 'failure' && steps.download-prov.outcome != 'failure' && steps.release.outcome != 'failure' }}
+          SUCCESS: ${{ steps.checkout-builder.outcome != 'failure' && steps.download-prov.outcome != 'failure' && steps.release.outcome != 'failure' && steps.release-new-tags.outcome != 'failure' && steps.release-tag-name.outcome != 'failure' }}
         run: |
           echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
 
