update
Signed-off-by: laurentsimon <laurentsimon@google.com>

diff --git a/.github/workflows/generator_container_slsa3.yml b/.github/workflows/generator_container_slsa3.yml
--- a/.github/workflows/generator_container_slsa3.yml
+++ b/.github/workflows/generator_container_slsa3.yml
@@ -21,6 +21,10 @@ env:
   BUILDER_BINARY: slsa-generator-container-linux-amd64 # Name of the binary in the release assets.
   BUILDER_DIR: internal/builders/container # Source directory if we compile the builder.
 
+defaults:
+  run:
+    shell: bash
+
 on:
   workflow_call:
     secrets:
@@ -50,12 +54,17 @@ on:
         required: false
         type: boolean
         default: false
+    outputs:
+      outcome:
+        description: "The outcome status of the run ('success' or 'failure')."
+        value: ${{ jobs.final.outputs.outcome }}
 
 jobs:
   # detect-env detects the reusable workflow's repository and ref for use later
   # in the workflow.
   detect-env:
     outputs:
+      outcome: ${{ steps.final.outputs.outcome }}
       repository: ${{ steps.detect.outputs.repository }}
       ref: ${{ steps.detect.outputs.ref }}
     runs-on: ubuntu-latest
@@ -64,7 +73,14 @@ jobs:
     steps:
       - name: Detect the generator ref
         id: detect
+        continue-on-error: true
         uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow@main
+      
+      - name: Final outcome
+        env:
+          SUCCESS: ${{ steps.detect.outcome != 'failure' }}
+        id: final
+        run: echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
 
   # generator builds the generator binary and runs it to generate SLSA
   # provenance.
@@ -76,6 +92,8 @@ jobs:
   # with the release at the ref detected by `detect-env`. This must be a tag
   # reference.
   generator:
+    outputs:
+      outcome: ${{ steps.final.outputs.outcome }}
     runs-on: ubuntu-latest
     needs: [detect-env]
     permissions:
@@ -84,6 +102,8 @@ jobs:
       packages: write # Needed to login and upload attestations to ghcr.io.
     steps:
       - name: Generate builder
+        id: generate-builder
+        continue-on-error: true
         uses: slsa-framework/slsa-github-generator/.github/actions/generate-builder@main
         with:
           repository: "${{ needs.detect-env.outputs.repository }}"
@@ -96,7 +116,12 @@ jobs:
           allow-private-repository: ${{ inputs.private-repository }}
 
       - uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # tag=v2.8.1
+        id: cosign-install
+        continue-on-error: true
+
       - name: Login
+        id: login
+        continue-on-error: true
         env:
           UNTRUSTED_IMAGE: "${{ inputs.image }}"
           UNTRUSTED_USERNAME: "${{ inputs.registry-username }}"
@@ -120,7 +145,7 @@ jobs:
 
       - name: Create and sign provenance
         id: sign-prov
-        shell: bash
+        continue-on-error: true
         env:
           UNTRUSTED_IMAGE: "${{ inputs.image }}"
           UNTRUSTED_DIGEST: "${{ inputs.digest }}"
@@ -136,3 +161,23 @@ jobs:
             --type slsaprovenance \
             --force \
             "${UNTRUSTED_IMAGE}@${UNTRUSTED_DIGEST}"
+
+      - name: Final outcome
+        env:
+          SUCCESS: ${{ steps.generate-builder.outcome != 'failure' && steps.cosign-install.outcome != 'failure' && steps.login.outcome != 'failure' && steps.sign-prov.outcome != 'failure' }}
+        id: final
+        run: echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
+  
+  # final outputs the return status of the reusable workflow run.
+  final:
+    outputs:
+      outcome: ${{ steps.final.outputs.outcome }}
+    runs-on: ubuntu-latest
+    needs: [detect-env, generator]
+    if: always()
+    steps:
+      - name: Final outcome
+        env:
+          SUCCESS: ${{ needs.detect-env.outputs.outcome != 'failure' && steps.generator.outputs.outcome != 'failure' }}
+        id: final
+        run: echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
