also for is-fork
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/pre-submit.actions-for-pr.yml b/.github/workflows/pre-submit.actions-for-pr.yml
--- a/.github/workflows/pre-submit.actions-for-pr.yml
+++ b/.github/workflows/pre-submit.actions-for-pr.yml
@@ -641,3 +641,10 @@ jobs:
         run: |
           set -euo pipefail
           echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> "$GITHUB_OUTPUT"
+      - name: Final outcome - is-fork
+        if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name 
+        env:
+          SUCCESS: ${{ steps.checkwithgithubtoken.outcome == 'failure' && steps.checkwithusertoken.outcome == 'failure' && steps.checkwitheithertoken.outcome == 'failure'}}
+        run: |
+          set -euo pipefail
+          echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> "$GITHUB_OUTPUT"
