e2e
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/pre-submit.actions-for-pr.yml b/.github/workflows/pre-submit.actions-for-pr.yml
--- a/.github/workflows/pre-submit.actions-for-pr.yml
+++ b/.github/workflows/pre-submit.actions-for-pr.yml
@@ -611,8 +611,33 @@ jobs:
         with:
           repository: ${{github.event.pull_request.head.repo.full_name}}
           ref: ${{ github.event.pull_request.head.sha }}
+      # All these jobs need a user-token with admin:read,
+      # so the the regular github.token will not be enough
+
+      # It's most conveniet if the toekn is named as a secret called "token",
+      # so you can access it with `secrets.token`.
+
+      # If this PR is from a fork, then all of these steps should fail because
+      # the base repo's secrets are not avaiable to forks.
       - uses: ./.github/actions/ensure-github-hosted-runners-js
         continue-on-error: true
         id: checkwithgithubtoken
         with:
           token: ${{ github.token }}
+      - uses: ./.github/actions/ensure-github-hosted-runners-js
+        continue-on-error: true
+        id: checkwithusertoken
+        with:
+          token: ${{ secrets.token }}
+      - uses: ./.github/actions/ensure-github-hosted-runners-js
+        continue-on-error: true
+        id: checkwitheithertoken
+        with:
+          token: ${{ secrets.token || github.token }}
+      - name: Final outcome - non-fork
+        if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name 
+        env:
+          SUCCESS: ${{ steps.checkwithgithubtoken.outcome == 'failure' && steps.checkwithusertoken.outcome != 'failure' && steps.checkwitheithertoken.outcome != 'failure'}}
+        run: |
+          set -euo pipefail
+          echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> "$GITHUB_OUTPUT"
